spring:
  application:
    name: order-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jordankarthikk/configuration.git

server:
  port: 9090


eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761